#!/usr/bin/php
<?php
require (__DIR__ . '/src/bootstrap.php');
use BigBIT\Oddin\Console\CacheGenerator;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new CacheGenerator());

$application->run();