#!/usr/bin/php
<?php
require (__DIR__ . '/src/Bootstrap.php');
use BigBIT\Oddin\Console\CacheGenerator;
use Symfony\Component\Console\Application;
use BigBIT\Oddin\Bootstrap;

Bootstrap::getContainer();

$application = new Application();

$application->add(new CacheGenerator());

$application->run();
