#!/usr/bin/php
<?php
use BigBIT\Oddin\Console\CacheGenerator;
use Symfony\Component\Console\Application;
use BigBIT\DIBootstrap\Bootstrap;

require_once(
    __DIR__ . '/vendor/bigbit/di-bootstrap/src/Bootstrap.php'
);
Bootstrap::detectVendorPath();

Bootstrap::getContainer();

$application = new Application();

$application->add(new CacheGenerator());

$application->run();
